version: '3.4'

services:
  mysql:
    image: 'mysql:8'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - './data/mysql:/var/lib/mysql:delegated'
    environment: 
      MYSQL_ROOT_PASSWORD: 'root'
  
  node-service-one:
    depends_on:
      - mysql
    build:
      context: '../rakenduste-programmeerimine-TA-I-node'
    ports:
      - '3001:3000'
    volumes:
      - '../rakenduste-programmeerimine-TA-I-node:/home/node/app:delegated'
    command: 'run start'

  node-service-two:
    depends_on:
      - mysql
    build:
      context: '../rakenduste-programmeerimine-TA-II-node'
    ports:
      - '3002:3000'
    volumes:
      - '../rakenduste-programmeerimine-TA-II-node:/home/node/app:delegated'
    command: 'run start'
